library (plyr)
library(splines)
library(tidyverse)
library(pander)
library(data.table)
x <- seq(from = 0, to = 6, by = .025)
y <- sin(2*x) + x -.1*x^2 + 2 + rnorm(length(x), sd = .3)
df = data.frame(x,y)
write.csv(df,"datapoints_1.csv", row.names = FALSE)